In [1]:
print('om namo narayana')

om namo narayana


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
'''def prediction(x, W):
    #here x is a numpy array representing a single input
    #this function must return a single float value
    activations =[]
    #activations is a 1D array
    activations.append(x)
    for layer in range(len(W)):
        activations.append(np.dot(np.array(activations[layer]).reshape(1, len(activations[layer])), W[layer]))
    return activations[len(activations) - 1]
    '''

'def prediction(x, W):\n    #here x is a numpy array representing a single input\n    #this function must return a single float value\n    activations =[]\n    #activations is a 1D array\n    activations.append(x)\n    for layer in range(len(W)):\n        activations.append(np.dot(np.array(activations[layer]).reshape(1, len(activations[layer])), W[layer]))\n    return activations[len(activations) - 1]\n    '

In [4]:
'''#input_data is a nupmy array
def SGD(input_data, output_data, dict ={}):
    log = {'epochs': 10, 'batch_size': len(input_data)/10, 'maximum_error':10e10 , 'dim_layer': [2, 3, 2], alpha = '0.01'}
    for key in log.keys():
        if(dict[key] != None):
            log[key] = dict[key]
    batch_size = log.get('batch_size')
    if(batch_size > input_data.shape[0]):
        print('invalid batch_size')
    dim_layer  = log.get('dim_layer')
    max_layer = max(dim_layer)
    #check this reshape 
    my_filter = []
    for layer in dim_layers:
        my_filter.append(list(np.ones(layer)) + np.zeros((max_layer - layer)))
    #check the dimension of filter
    my_filter = np.array(my_filter)
    input_data = np.array(list(input_data) + list(input_data[:len(input_data)%batch_size])).reshape(len(input_data)/batch_size, batch_size, len(input_data[0]))
    for epoch in range(log.get('epochs')):
        W = np.random.randint(1, 10, [len(dim_layers) - 1, max_layer, max_layer])
        #bias = np.random.randint(1, 10, [len(dim_layers) - 1, max_layer])
        for batch in range(len(input_data)/batch_size):
            X = batch_size(batch*len(input_data[0]), (batch + 1)*len(input_data[0]))
            predictions = [prediction(X[i]) for i in range(batch_size)]
                activations = []
                activations.append(X[data])
                for layer in range(len(dim_layer) - 2):
                    #check the dimensions properly
                    activations.append(np.dot(activation[layer] ,W[layer][:dim_layer[layer] + 1])) 
            #lengh of activations and weights should be len(dim_layer) - 1
            #W[1].shape = (3, 2)
            #W[0].shape = (2, 3)
            #dif.shape = (1, 2)
            #x.shape = (1, 2)
            #np.dot(dif, W[1].T).shape  = (1, 3)
            #np.dot(W[1])
            #single output is a 1D array
            #activations[0] is a 1D array
            #dif is a 1_D array
            
            A = W[:]
            dif = np.array(activations[len(activations) - 1] - y_train).mean(axis = 0)
            W[1] -= alpha*np.dot(activations[1].reshape(len(activations[1]), 1) , dif.reshape(1, len(dif)))
            #bias[1] -= alpha * dif
            matrix =  np.dot(dif.reshape(1, len(dif)), A[1].T)
            W[0] -=  alpha * np.dot(activations[0].reshape(len(activations[0]), 1), matrix.reshape(1, len(matrix)))'''

"#input_data is a nupmy array\ndef SGD(input_data, output_data, dict ={}):\n    log = {'epochs': 10, 'batch_size': len(input_data)/10, 'maximum_error':10e10 , 'dim_layer': [2, 3, 2], alpha = '0.01'}\n    for key in log.keys():\n        if(dict[key] != None):\n            log[key] = dict[key]\n    batch_size = log.get('batch_size')\n    if(batch_size > input_data.shape[0]):\n        print('invalid batch_size')\n    dim_layer  = log.get('dim_layer')\n    max_layer = max(dim_layer)\n    #check this reshape \n    my_filter = []\n    for layer in dim_layers:\n        my_filter.append(list(np.ones(layer)) + np.zeros((max_layer - layer)))\n    #check the dimension of filter\n    my_filter = np.array(my_filter)\n    input_data = np.array(list(input_data) + list(input_data[:len(input_data)%batch_size])).reshape(len(input_data)/batch_size, batch_size, len(input_data[0]))\n    for epoch in range(log.get('epochs')):\n        W = np.random.randint(1, 10, [len(dim_layers) - 1, max_layer, max_layer])

In [5]:
'''def trial(a = {'a':1, 'b':2}):
    b = {'a':1, 'b':2}
    print(a.get('a'), a.get('b'))
    for key in b.keys():
        if a.get(key) != None:
            b[key] = a[key]
        print(b.get(key))
trial({'a':3})'''

"def trial(a = {'a':1, 'b':2}):\n    b = {'a':1, 'b':2}\n    print(a.get('a'), a.get('b'))\n    for key in b.keys():\n        if a.get(key) != None:\n            b[key] = a[key]\n        print(b.get(key))\ntrial({'a':3})"

In [6]:
'''A = np.random.randint(1, 3, [3, 2])
B = np.random.randint(1, 3 ,[2, 3])
O = np.random.randint(1, 3, [1, 2])
I = np.random.randint(1, 3, [1, 3])
print(A.tolist())
print(B.tolist())
print(np.dot(A, B).shape)
print(np.dot(B, A).shape)
#print(np.dot(O, A))
print(np.dot(O, A.T))
print(np.dot(A.T, O))#invalid'''

'A = np.random.randint(1, 3, [3, 2])\nB = np.random.randint(1, 3 ,[2, 3])\nO = np.random.randint(1, 3, [1, 2])\nI = np.random.randint(1, 3, [1, 3])\nprint(A.tolist())\nprint(B.tolist())\nprint(np.dot(A, B).shape)\nprint(np.dot(B, A).shape)\n#print(np.dot(O, A))\nprint(np.dot(O, A.T))\nprint(np.dot(A.T, O))#invalid'

In [7]:
'''activation = np.random.randint(1, 3, [3,])
A = np.random.randint(1, 4, [2, 3])
print(activation.tolist(), A.tolist())
print(np.dot(A, activation).tolist())'''

'activation = np.random.randint(1, 3, [3,])\nA = np.random.randint(1, 4, [2, 3])\nprint(activation.tolist(), A.tolist())\nprint(np.dot(A, activation).tolist())'

In [8]:
'''activation = np.random.randint(1, 3, [2,])
A = np.random.randint(1, 4, [2, 3])
print(activation.tolist(), A.tolist())
print(np.dot(A.T, activation).tolist())
print(np.dot(A, activation.T).tolist())'''

'activation = np.random.randint(1, 3, [2,])\nA = np.random.randint(1, 4, [2, 3])\nprint(activation.tolist(), A.tolist())\nprint(np.dot(A.T, activation).tolist())\nprint(np.dot(A, activation.T).tolist())'

In [9]:
'''activation = np.random.randint(1, 3, [1, 3])
A = np.random.randint(1, 4, [2, 3])
print(activation.tolist(), A.tolist())
print(np.dot(A, activation).tolist())'''

'activation = np.random.randint(1, 3, [1, 3])\nA = np.random.randint(1, 4, [2, 3])\nprint(activation.tolist(), A.tolist())\nprint(np.dot(A, activation).tolist())'

In [10]:
'''A = np.arange(1, 5).reshape(2 , 2)
print(A)
B = np.arange(5, 9).reshape(2, 2)
print(B)
print(np.dot(A, B.T).tolist())
print(np.dot(B.T, A).tolist())
print(np.dot(A.T, B).tolist())
print(np.dot(B, A.T).tolist())
print(np.dot(A, B).tolist())
print(np.dot(B, A).tolist())'''

'A = np.arange(1, 5).reshape(2 , 2)\nprint(A)\nB = np.arange(5, 9).reshape(2, 2)\nprint(B)\nprint(np.dot(A, B.T).tolist())\nprint(np.dot(B.T, A).tolist())\nprint(np.dot(A.T, B).tolist())\nprint(np.dot(B, A.T).tolist())\nprint(np.dot(A, B).tolist())\nprint(np.dot(B, A).tolist())'

In [48]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [49]:
def sigmoid_derivative(z):
    return np.exp(-z)/(1 + np.exp(-z))**2

In [50]:
def get_random_W(dim_layer):
    W = []
    for layer in range(len(dim_layer) - 1):
        W.append(np.random.randint(1, 4, [dim_layer[layer], dim_layer[layer+1]]) *1.0)
    return W
    #W is a 3D list

In [51]:
def get_random_bias(dim_layer):
    bias = []

    for layer in range(len(dim_layer) - 1):
        bias.append(np.random.randint(1, 3, [dim_layer[layer+1]]) * 1.0)
    return bias
    #bias is a 2D list

In [60]:
def get_activations(X, W, bias):
    X = np.array(X)
    activations = []
    input_values = []
    input_values.append(X)
    activations.append(sigmoid(X))
    for layer in range(len(W)):
        input_values.append(np.dot(W[layer].T, (activations[layer]).reshape(activations[layer].shape[0], 1)).T[0])
        activations.append(np.dot(W[layer].T, sigmoid(activations[layer]).reshape(activations[layer].shape[0], 1)).T[0] + bias[layer])
    return activations, input_values
    #activations is a 2D list

In [53]:
def get_prediction(X, W, bias):
    activations = sigmoid(X)
    for layer in range(len(W)):
        activations = np.dot(W[layer].T, sigmoid(activations).reshape(activations.shape[0], 1)).T[0] + bias[layer]
    return activations

In [67]:
def back_prop(X, Y, W, b, activations, input_values, dim_layer, alpha):
    A = W[:]
    l = len(dim_layer) - 1
    matrix = np.product([list(np.array(activations[l] - Y)), list(np.array(sigmoid_derivative(input_values[l])))], axis = 0)
    for i in range(len(dim_layer) - 1):
        W[l - 1 - i] = A[l - 1 - i] - alpha *  np.dot(activations[l - i - 1].reshape(activations[l - 1 - i].shape[0], 1) , matrix.reshape(1, len(matrix))) 
        b[l - 1 - i] -= alpha * matrix
        matrix = np.product([list(np.dot(matrix.reshape(1, matrix.shape[0]), A[l - 1 - i].T)[0]), list(np.array(sigmoid_derivative(input_values[l - 1 - i])))], axis = 0)
        #while inner product matrix is converted to shape (1, x)
    return(W, b)

In [55]:
def get_error(X, Y, W ,bias):
    #X is a single input numpy array and Y is the single output numpy array
    predictions = get_prediction(X, W, bias)
    error = sum((predictions - Y)**2)
    return error

In [56]:
def evaluate(input_test_data, output_test_data, W, bias):
    predictions = np.array([get_prediction(input_test_data[i], W, bias) for i in range(input_test_data.shape[0])])
    error = np.sum((predictions/pow(input_test_data.shape[0], 0.5) - output_test_data/pow(input_test_data.shape[0], 0.5))**2)
    return error

In [62]:
#input_data is a nupmy array
def mini_SGD(input_data, output_data, input_test_data, output_test_data, dict_ ={}):
    
    
    log = {'epochs': 10, 'maximum_error':10e10 , 'dim_layer': [2, 3, 2], 'alpha' : 0.01}
    for key in log.keys():
        if(dict_[key] != None):
            log[key] = dict_[key]
    dim_layer  = log.get('dim_layer')
    alpha = log.get('alpha')
    error_list = []
    weight_list = []
    
    
    for epoch in range(log.get('epochs')):
        print('\n\nepoch_number:{}'.format(epoch+1))
        W = get_random_W(dim_layer)
        bias = get_random_bias(dim_layer)

        for i in range(input_data.shape[0]):
            activations, input_values = get_activations(input_data[i], W, bias)
            W, bias = back_prop(input_data[i], output_data[i], W, bias, activations, input_values, dim_layer, log.get('alpha'))
            error = get_error(input_data[i], output_data[i], W, bias)
            #print('{} :error: {}'.format(i+1, error))
        batch_error = evaluate(input_test_data, output_test_data, W, bias)
        error_list.append(batch_error)
        weight_list.append((W, bias))
        print('batch_error:{}'.format(batch_error))
        #print('error:{}'.format(error))
    return weight_list[error_list.index(min(error_list))], min(error_list)

In [63]:
input_data = np.random.randint(1, 100, [10000, 2])
output_data = input_data * 3.0
input_test_data = np.random.randint(1, 100, [100, 2])
output_test_data = input_test_data * 3.0

In [ ]:
A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs': 100, 'maximum_error':10e10 , 'dim_layer': [2, 3, 2], 'alpha' : 0.0000001})
print(A)
print(error)



epoch_number:1
batch_error:55827.54731780512


epoch_number:2
batch_error:55679.19524765906


epoch_number:3
batch_error:55675.992570992035


epoch_number:4
batch_error:54239.66497361036


epoch_number:5
batch_error:57076.89145634726


epoch_number:6
batch_error:55365.46396640734


epoch_number:7
batch_error:55221.91476381538


epoch_number:8
batch_error:55955.735982695944


epoch_number:9
batch_error:55708.734108034594


epoch_number:10
batch_error:55976.77465179565


epoch_number:11
batch_error:55160.22110335485


epoch_number:12
batch_error:54827.50105001129


epoch_number:13
batch_error:55697.05193938805


epoch_number:14
batch_error:55401.93576737867


epoch_number:15
batch_error:54252.88622424412


epoch_number:16
batch_error:55462.178329963914


epoch_number:17
batch_error:55671.08095197701


epoch_number:18
batch_error:55109.96788197823


epoch_number:19
batch_error:55317.35187477709


epoch_number:20
batch_error:57318.98636621245


epoch_number:21
batch_error:56569.657459308

In [21]:
def f1(alpha, epochs):
    input_data = np.random.randint(1, 100, [10000, 1])
    output_data = input_data * 2
    print(output_data.shape)
    print
    input_test_data = np.random.randint(1, 100, [100, 1])
    output_test_data = input_test_data * 2
    print('*********WITH 1 HIDDEN LAYER***********\n\n\n')
    A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs':epochs, 'maximum_error':10e10, 'dim_layer': [1, 1, 1], 'alpha' : alpha })
    print('min error',error)
    print('\n\n\n*********WITH 1 HIDDEN LAYER***********')
    print('*********2 PERCEPTRON IN HIDDEN LAYER********\n\n\n')
    A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs':epochs, 'maximum_error':10e10, 'dim_layer': [1, 2, 1], 'alpha' : alpha })
    print('min error', error)
    print('\n\n\n*********WITH 2 HIDDEN LAYERS**********\n\n\n')
    A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs':epochs, 'maximum_error':10e10, 'dim_layer': [1, 1, 1, 1], 'alpha' : alpha })
    print('min error', error)

In [22]:
def f2(alpha, epochs):
    input_data = np.random.randint(1, 100, [10000, 2])
    output_data = (input_data.T[0] * 3 + input_data.T[1] * 4).reshape(input_data.shape[0], 1)
    input_test_data = np.random.randint(1, 100, [100, 2])
    output_test_data = (input_test_data.T[0] * 3 + input_test_data.T[1] * 4).reshape(input_test_data.shape[0], 1)
    print('*********WITH 1 HIDDEN LAYER***********\n\n\n')
    A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs':epochs, 'maximum_error':10e10, 'dim_layer': [2, 1, 1], 'alpha' : alpha })
    print(error)
    print('\n\n\n*********WITH 1 HIDDEN LAYER***********')
    print('*********2 PERCEPTRON IN HIDDEN LAYER********\n\n\n')
    A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs':epochs, 'maximum_error':10e10, 'dim_layer': [2, 2, 1], 'alpha' : alpha })
    print(error)
    print('\n\n\n*********WITH 2 HIDDEN LAYERS**********\n\n\n')
    A, error = mini_SGD(input_data, output_data, input_test_data, output_test_data, {'epochs':epochs, 'maximum_error':10e10, 'dim_layer': [2, 1, 1], 'alpha' : alpha })
    print(error)

In [23]:
f1(0.0000001, 10)#with alpha value 0.0000001

(10000, 1)
*********WITH 1 HIDDEN LAYER***********





epoch_number:1
batch_error:7.007007586480496


epoch_number:2
batch_error:2.4084634125573783


epoch_number:3
batch_error:4.812040592928824


epoch_number:4
batch_error:1.2036133245853051


epoch_number:5
batch_error:9.680900862991043


epoch_number:6
batch_error:5.196078926490138


epoch_number:7
batch_error:1.2363773087563483


epoch_number:8
batch_error:2.4327519943810976


epoch_number:9
batch_error:2.4386244517471725


epoch_number:10
batch_error:4.812040592928824


epoch_number:11
batch_error:5.196078926490138


epoch_number:12
batch_error:2.4852018460487004


epoch_number:13
batch_error:7.007007586480496


epoch_number:14
batch_error:2.4852018460487004


epoch_number:15
batch_error:3.464443878844351


epoch_number:16
batch_error:2.4084634125573783


epoch_number:17
batch_error:4.070565016205041


epoch_number:18
batch_error:13.147690680210893


epoch_number:19
batch_error:13.147690680210893


epoch_number:20
batch_error:2.4

KeyboardInterrupt: 

In [ ]:
f2(0.0000001, 10)#with alpha value 0.0000001

In [ ]:
f1(0.00001, 5)

In [ ]:
f1(0.00005, 1)

In [ ]:
f1(0.00003, 1)

In [ ]:
f1(0.00003, 1)

In [ ]:
#best for f1 0.00005 for 1 and 0.00002 for next 2

In [ ]:
#best for f2 is 0.00003 

In [26]:
sigmoid(np.arange(1, 10))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [44]:
a = np.random.randint(1, 4, [10])
b = np.random.randint(1, 4 ,[10])
print(a)
print(b)
c = [list(a), list(b)]
print (c)

[3 2 2 3 1 3 2 1 3 1]
[2 3 1 3 2 1 2 1 3 1]
[[3, 2, 2, 3, 1, 3, 2, 1, 3, 1], [2, 3, 1, 3, 2, 1, 2, 1, 3, 1]]


In [46]:
print(np.product(c, axis = 0))

[6 6 2 9 2 3 4 1 9 1]
